name: pwhl_flutter
description: "A mobile application to show PWHL scores, schedules, stats, and more"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  live_indicator: ^0.0.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icon/
